activation: gelu
attn: full
batch_size: 512
c_out: 1
cols:
- XOM_logpctchange
- CVX_logpctchange
- COP_logpctchange
- BP_logpctchange
- PBR_logpctchange
- WTI_logpctchange
- EOG_logpctchange
- ENB_logpctchange
- SLB_logpctchange
d_ff: 4096
d_model: 512
data_path: full_1h.csv
# date_end: '2020-01-01'
# date_start: '2012-01-01'
# date_test: '2019-06-01'
des: HypOptStockOil
distil: false
dont_shuffle_train: false
dropout: 0.5
dropout_emb: 0.0
e_layers: 3
emb_t2v_app_dim: 16
enc_in: 9
factor: 5
features: MS
final_mode: mode3
freq: h
inverse_output: false
inverse_pred: true
label_len: 0
learning_rate: 1.0e-04
ln_mode: post
loss: stock_tanhv1
lradj: type3
max_epochs: 30
mix: false
model: stockformer
n_heads: 6
no_early_stop: false
no_scale_mean: true
optim: Adam
output_attention: false
patience: 1000
pre_epochs: 10
pre_loss: "stock_tanhv4"
pred_len: 1
root_path: ./data/stock/
scale: true
seed: 5
seq_len: 16
t_embed: time2vec_add
target: XOM_logpctchange
tok_emb: default
